site_name: Mémo AIS
site_description: Mémo formation AIS
site_author: Olivier
repo_name: memo-ais
docs_dir: docs
site_dir: site

theme:
  name: material
  custom_dir: overrides
  logo: assets/img/brand/olidev-logo.png
  language: fr
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search

extra_css:
  - assets/stylesheets/custom.css

extra_javascript:
  - assets/javascripts/mermaid-zoom.js
  - assets/javascripts/image-zoom.js

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Accueil: index.md
  - Intro à l'AIS:
      - Présentation: intro-ais/index.md
      - Matériel: intro-ais/materiel.md
      - Système et Linux: intro-ais/systeme-linux.md
      - Réseau: intro-ais/reseau.md
      - Commandes Linux: intro-ais/commandes-linux.md
      - Cybersécurité:
          - Bases: intro-ais/securite.md
          - Acteurs et rôles: intro-ais/securite-acteurs.md
          - Menaces et attaques: intro-ais/securite-menaces.md
          - Hygiène numérique: intro-ais/hygiene-numerique.md
          - Chiffrement: intro-ais/chiffrement.md
  - Système d’info & archi SI:
      - Présentation: systeme-info-si/index.md
      - Le système d'information:
          - Vue d'ensemble: systeme-info-si/iteration-1/index.md
          - Cas concret SI: systeme-info-si/iteration-1/cas-concret-si.md
          - Première vue globale du SI: systeme-info-si/iteration-1/premiere-vue-globale-si.md
          - Diagramme réseau du SI: systeme-info-si/iteration-1/diagramme-reseau-si.md
          - Cartographie des utilisateurs: systeme-info-si/iteration-1/cartographie-utilisateurs.md
          - Modèles d'architecture applicative: systeme-info-si/iteration-1/modeles-architecture-applicative.md
          - Dépendances applicatives: systeme-info-si/iteration-1/dependances-applicatives.md
          - Diagrammes finaux & résumé: systeme-info-si/iteration-1/finalisation-diagrammes.md
      - Enjeux clés d'un SI:
          - Vue d'ensemble: systeme-info-si/iteration-2/index.md
          - Enjeux d'un SI à partir du réel: systeme-info-si/iteration-2/enjeux-si-reel.md
          - Identifier et prioriser les risques: systeme-info-si/iteration-2/risques-si.md
          - Introduction aux normes SI: systeme-info-si/iteration-2/normes-si.md
          - Synthèse enjeux, risques et normes: systeme-info-si/iteration-2/synthese-enjeux-risques-normes.md
      - Analyse d'une architecture SI:
          - Vue d'ensemble: systeme-info-si/iteration-3/index.md
          - Choisir un cas d'étude SI: systeme-info-si/iteration-3/choisir-cas.md
          - Cartographie du SI: systeme-info-si/iteration-3/cartographie-si.md
          - Analyse des usages et des risques: systeme-info-si/iteration-3/analyse-usages-risques.md
          - Propositions d'amélioration: systeme-info-si/iteration-3/propositions-amelioration.md
          - Préparation de la restitution: systeme-info-si/iteration-3/preparation-restitution.md
      - Sécurité d'un SI:
          - Vue d'ensemble: systeme-info-si/iteration-4/index.md
          - Analyse des incidents et mitigation: systeme-info-si/iteration-4/analyse-incidents-mitigation.md
          - Amélioration architecture CHU Rouen: systeme-info-si/iteration-4/amelioration-architecture-chu-rouen.md
          - Mémo personnel final: systeme-info-si/iteration-4/memo-personnel-final.md

  - Administration des réseaux :
      - Vue d'ensemble: admin-reseaux/index.md
      - Fondations TCP/IP et adressage :
          - Vue d'ensemble: admin-reseaux/iteration-1/index.md
          - Fondations TCP/IP & capture : admin-reseaux/iteration-1/fondations-tcpip-capture.md
          - Exercices Wireshark: admin-reseaux/iteration-1/wireshark.md
          - Adressage IPv4 et subnetting: admin-reseaux/iteration-1/adressage-ipv4-subnetting.md
          - Schémas réseau L1/L2/L3: admin-reseaux/iteration-1/ schémas_réseau_L1_L2_L3.md
          - Schéma réseau annoté : admin-reseaux/iteration-1/schema-reseau-alpesnet-complet.md

  - Pense-bête:
      - Vue d'ensemble: pense-bete/index.md
      - Intro AIS: pense-bete/intro-ais.md
      - Linux et commandes: pense-bete/linux.md
      - Réseau: pense-bete/reseau.md
      - Cybersécurité: pense-bete/cybersecurite.md
      - Système d’info & archi SI:
          - Vue d'ensemble: pense-bete/systeme-info-si.md
          - Cartographie et architecture: pense-bete/systeme-info-si-cartographie.md
          - Risques, incidents et enjeux: pense-bete/systeme-info-si-risques.md
          - Vocabulaire SI: pense-bete/systeme-info-si-vocabulaire.md
          - Diagrammes SI: pense-bete/systeme-info-si-diagrammes.md
      - Administration des réseaux: 
          - administration des réseaux - Vue d'ensemble: pense-bete/admin-reseaux.md
          - administration des réseaux - alpesnet : pense-bete/admin-reseaux-alpesnet.md
          - administration des réseaux - commandes: pense-bete/admin-reseaux-commandes.md
          - administration des réseaux - installation: pense-bete/admin-reseaux-installation.md
          - administration des réseaux - modèles: pense-bete/admin-reseaux-modeles.md
          - administration des réseaux - niveaux: pense-bete/admin-reseaux-niveaux.md
          - administration des réseaux - protocoles: pense-bete/admin-reseaux-protocoles.md
  - Liens utiles: liens-utiles.md
