site_name: Mémo AIS
site_description: Mémo formation AIS
site_author: Olivier
repo_name: memo-ais
docs_dir: docs
site_dir: site

theme:
  name: material
  custom_dir: overrides
  logo: assets/img/brand/olidev-logo.png
  language: fr
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search

extra_css:
  - assets/stylesheets/custom.css

extra_javascript:
  - assets/javascripts/mermaid-zoom.js
  - assets/javascripts/image-zoom.js
  - assets/javascripts/pdf-viewer.js

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Accueil: index.md
  - Intro à l'AIS:
      - Présentation: intro-ais/index.md
      - Matériel: intro-ais/materiel.md
      - Système et Linux: intro-ais/systeme-linux.md
      - Réseau: intro-ais/reseau.md
      - Commandes Linux: intro-ais/commandes-linux.md
      - Cybersécurité:
          - Bases: intro-ais/securite.md
          - Acteurs et rôles: intro-ais/securite-acteurs.md
          - Menaces et attaques: intro-ais/securite-menaces.md
          - Hygiène numérique: intro-ais/hygiene-numerique.md
          - Chiffrement: intro-ais/chiffrement.md

  - Système d’info & archi SI:
      - Présentation: systeme-info-si/index.md
      - Mémo personnel : systeme-info-si/synthese-personnel-final.md
      - Le système d'information:
          - Vue d'ensemble: systeme-info-si/iteration-1/index.md
          - Cas concret SI: systeme-info-si/iteration-1/cas-concret-si.md
          - Première vue globale du SI: systeme-info-si/iteration-1/premiere-vue-globale-si.md
          - Diagramme réseau du SI: systeme-info-si/iteration-1/diagramme-reseau-si.md
          - Cartographie des utilisateurs: systeme-info-si/iteration-1/cartographie-utilisateurs.md
          - Modèles d'architecture applicative: systeme-info-si/iteration-1/modeles-architecture-applicative.md
          - Dépendances applicatives: systeme-info-si/iteration-1/dependances-applicatives.md
          - Diagrammes finaux & résumé: systeme-info-si/iteration-1/finalisation-diagrammes.md
      - Enjeux clés d'un SI:
          - Vue d'ensemble: systeme-info-si/iteration-2/index.md
          - Enjeux d'un SI à partir du réel: systeme-info-si/iteration-2/enjeux-si-reel.md
          - Identifier et prioriser les risques: systeme-info-si/iteration-2/risques-si.md
          - Introduction aux normes SI: systeme-info-si/iteration-2/normes-si.md
          - Synthèse enjeux, risques et normes: systeme-info-si/iteration-2/synthese-enjeux-risques-normes.md
      - Analyse d'une architecture SI:
          - Vue d'ensemble: systeme-info-si/iteration-3/index.md
          - Choisir un cas d'étude SI: systeme-info-si/iteration-3/choisir-cas.md
          - Cartographie du SI: systeme-info-si/iteration-3/cartographie-si.md
          - Analyse des usages et des risques: systeme-info-si/iteration-3/analyse-usages-risques.md
          - Propositions d'amélioration: systeme-info-si/iteration-3/propositions-amelioration.md
          - Préparation de la restitution: systeme-info-si/iteration-3/preparation-restitution.md
      - Sécurité d'un SI:
          - Vue d'ensemble: systeme-info-si/iteration-4/index.md
          - Analyse des incidents et mitigation: systeme-info-si/iteration-4/analyse-incidents-mitigation.md
          - Amélioration architecture CHU Rouen: systeme-info-si/iteration-4/amelioration-architecture-chu-rouen.md

  - RGPD:
      - Présentation: rgpd/index.md
      - Définition et enjeux basiques: rgpd/definition-enjeux-basiques.md
      - Historique du RGPD: rgpd/historique.md
      - Acteurs du RGPD: rgpd/acteurs.md
      - Les 8 règles d'or: rgpd/regles-or.md
      - RGPD en collectivité: rgpd/collectivites.md
      - Travail et données personnelles: rgpd/travail-donnees-personnelles.md
      - Ressources PDF: rgpd/ressources-pdf.md
      - Enjeux avancés: rgpd/enjeux-avances.md

  - Administration des réseaux :
      - Vue d'ensemble: admin-reseaux/index.md
      - Synthèse personnelle CC-01: admin-reseaux/synthese-personnelle-cc01.md

      - Fondations TCP/IP et adressage :
          - Vue d'ensemble: admin-reseaux/iteration-1/index.md
          - Fondations TCP/IP & capture : admin-reseaux/iteration-1/fondations-tcpip-capture.md
          - Exercices Wireshark: admin-reseaux/iteration-1/wireshark.md
          - Adressage IPv4 et subnetting: admin-reseaux/iteration-1/adressage-ipv4-subnetting.md
          - Schémas réseau L1/L2/L3: admin-reseaux/iteration-1/ schémas_réseau_L1_L2_L3.md
          - Schéma réseau annoté : admin-reseaux/iteration-1/schema-reseau-alpesnet-complet.md
      - Commutation et Vlans:
          - Vue d'ensemble: admin-reseaux/iteration-2/index.md
          - Commutation et VLANs: admin-reseaux/iteration-2/synthese_switching_arp_stp.md
          - GNS3 tables mac & arp: admin-reseaux/iteration-2/gns3_mac_arp.md
          - Synthese VLANs: admin-reseaux/iteration-2/synthese_vlans.md
          - exercice facultatif - STP avancé : admin-reseaux/iteration-2/stp_avance.md
      - Routage:
          - Vue d'ensemble: admin-reseaux/iteration-3/index.md
          - Routage statique: admin-reseaux/iteration-3/routage-statique.md
          - Routage dynamique: admin-reseaux/iteration-3/routage-dynamique-OSPF.md
      - Services réseau:
          - Vue d'ensemble: admin-reseaux/iteration-4/index.md
          - Synthèse DHCP: admin-reseaux/iteration-4/synthese-dhcp.md
          - TP DHCP et VLANs: admin-reseaux/iteration-4/dhcp-vlans-gns3.md
          - Nat et PAT: admin-reseaux/iteration-4/nat-pat.md
          - TP NAT/PAT GNS3: admin-reseaux/iteration-4/tp-nat-pat-gns3.md
          - DNS interne: admin-reseaux/iteration-4/dns.md
          - Finalisation AlpesNet: admin-reseaux/iteration-4/finalisation-infrastructure-alpesnet.md
      - Analyse de trafic, diagnostic et clôture :
          - Vue d'ensemble: admin-reseaux/iteration-5/index.md
          - Méthode de diagnostic OSI: admin-reseaux/iteration-5/methode-diagnostic-osi.md
          - Simulation pannes AlpesNet OSI: admin-reseaux/iteration-5/simulation-pannes-alpesnet-osi.md
          - Critères fiche dépannage AlpesNet: admin-reseaux/iteration-5/criteres-fiche-depannage-alpesnet.md
          - TP Wireshark GNS3 et réseau physique: admin-reseaux/iteration-5/tp-wireshark-gns3-reseau-physique.md
          - Synthèse automatisation Bash: admin-reseaux/iteration-5/synthese-automatisation-bash.md
          - Automatisation connectivité et sauvegarde: admin-reseaux/iteration-5/automatisation-connectivite-sauvegarde.md

  - Administration des réseaux Sécurisation :
    - Vue d'ensemble: admin-reseaux-securisation/index.md
    - Segmentation sécurisée et filtrage réseau : 
        - Vue d'ensemble: admin-reseaux-securisation/it-1/index.md
        - Introduction du module et architecture sécurisée: admin-reseaux-securisation/it-1/atelier1.md
        - VLANs sécurisés et préparation du filtrage: admin-reseaux-securisation/it-1/atelier2.md
        - Filtrage réseau avec nftables: admin-reseaux-securisation/it-1/atelier3.md
        - Introduction au VLAN Hopping et tests d'attaque: admin-reseaux-securisation/it-1/atelier4.md
    - Pare-feu pfSense, journalisation et validation du cloisonnement réseau :
        - Vue d'ensemble: admin-reseaux-securisation/it-2/index.md
        - Déploiement de pfSense: admin-reseaux-securisation/it-2/atelier1.md

  - Pense-bête:
      - Vue d'ensemble: pense-bete/index.md
      - Intro AIS: pense-bete/intro-ais/intro-ais.md
      - Linux et commandes: pense-bete/intro-ais/linux.md
      - Réseau: pense-bete/intro-ais/reseau.md
      - Cybersécurité: pense-bete/intro-ais/cybersecurite.md
      - Système d’info & archi SI:
          - Vue d'ensemble: pense-bete/systeme-info/systeme-info-si.md
          - Cartographie et architecture: pense-bete/systeme-info/systeme-info-si-cartographie.md
          - Risques, incidents et enjeux: pense-bete/systeme-info/systeme-info-si-risques.md
          - Vocabulaire SI: pense-bete/systeme-info/systeme-info-si-vocabulaire.md
          - Diagrammes SI: pense-bete/systeme-info/systeme-info-si-diagrammes.md
      - Administration des réseaux:
          - Vue d'ensemble: pense-bete/admin-resau/admin-reseaux.md
          - AlpesNet: pense-bete/admin-resau/admin-reseaux-alpesnet.md
          - Commandes: pense-bete/admin-resau/admin-reseaux-commandes.md
          - Installation: pense-bete/admin-resau/admin-reseaux-installation.md
          - Modèles: pense-bete/admin-resau/admin-reseaux-modeles.md
          - Niveaux: pense-bete/admin-resau/admin-reseaux-niveaux.md
          - Protocoles: pense-bete/admin-resau/admin-reseaux-protocoles.md
          - Diagnostic, Wireshark et automatisation: pense-bete/admin-resau/diagnostic-wireshark-automatisation.md
          - Vocabulaire du routage: pense-bete/admin-resau/routage-vocabulaire.md
          - Switching, ARP, VLANs et STP: pense-bete/admin-resau/switching-arp-vlans.md

  - Liens utiles: liens-utiles.md
