site_name: Mémo AIS
site_description: Mémo formation AIS
site_author: Olivier
repo_name: memo-ais
docs_dir: docs
site_dir: site

theme:
  name: material
  custom_dir: overrides
  logo: assets/img/brand/olidev-logo.png
  language: fr
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search

extra_css:
  - assets/stylesheets/custom.css

extra_javascript:
  - assets/javascripts/mermaid-zoom.js
  - assets/javascripts/image-zoom.js
  - assets/javascripts/pdf-viewer.js
  - assets/javascripts/nav-accordion-v2.js

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Accueil: index.md
  - Intro à l'AIS:
      - Présentation: intro-ais/index.md
      - Matériel: intro-ais/materiel.md
      - Système et Linux: intro-ais/systeme-linux.md
      - Réseau: intro-ais/reseau.md
      - Commandes Linux: intro-ais/commandes-linux.md
      - Cybersécurité:
          - Bases: intro-ais/securite.md
          - Acteurs et rôles: intro-ais/securite-acteurs.md
          - Menaces et attaques: intro-ais/securite-menaces.md
          - Hygiène numérique: intro-ais/hygiene-numerique.md
          - Chiffrement: intro-ais/chiffrement.md

  - SI & archi:
      - Présentation: systeme-info-si/index.md
      - Mémo personnel : systeme-info-si/synthese-personnel-final.md
      - Itération 1 - Système d'information:
          - Vue d'ensemble: systeme-info-si/iteration-1/index.md
          - Cas concret SI: systeme-info-si/iteration-1/cas-concret-si.md
          - Première vue globale du SI: systeme-info-si/iteration-1/premiere-vue-globale-si.md
          - Diagramme réseau du SI: systeme-info-si/iteration-1/diagramme-reseau-si.md
          - Cartographie des utilisateurs: systeme-info-si/iteration-1/cartographie-utilisateurs.md
          - Modèles d'architecture applicative: systeme-info-si/iteration-1/modeles-architecture-applicative.md
          - Dépendances applicatives: systeme-info-si/iteration-1/dependances-applicatives.md
          - Diagrammes finaux & résumé: systeme-info-si/iteration-1/finalisation-diagrammes.md
      - Itération 2 - Enjeux, risques et normes:
          - Vue d'ensemble: systeme-info-si/iteration-2/index.md
          - Enjeux d'un SI à partir du réel: systeme-info-si/iteration-2/enjeux-si-reel.md
          - Identifier et prioriser les risques: systeme-info-si/iteration-2/risques-si.md
          - Introduction aux normes SI: systeme-info-si/iteration-2/normes-si.md
          - Synthèse enjeux, risques et normes: systeme-info-si/iteration-2/synthese-enjeux-risques-normes.md
      - Itération 3 - Analyse d'architecture SI:
          - Vue d'ensemble: systeme-info-si/iteration-3/index.md
          - Choisir un cas d'étude SI: systeme-info-si/iteration-3/choisir-cas.md
          - Cartographie du SI: systeme-info-si/iteration-3/cartographie-si.md
          - Analyse des usages et des risques: systeme-info-si/iteration-3/analyse-usages-risques.md
          - Propositions d'amélioration: systeme-info-si/iteration-3/propositions-amelioration.md
          - Préparation de la restitution: systeme-info-si/iteration-3/preparation-restitution.md
      - Itération 4 - Sécurité d'un SI:
          - Vue d'ensemble: systeme-info-si/iteration-4/index.md
          - Analyse des incidents et mitigation: systeme-info-si/iteration-4/analyse-incidents-mitigation.md
          - Amélioration architecture CHU Rouen: systeme-info-si/iteration-4/amelioration-architecture-chu-rouen.md

  - RGPD:
      - Présentation: rgpd/index.md
      - Définition et enjeux basiques: rgpd/definition-enjeux-basiques.md
      - Historique du RGPD: rgpd/historique.md
      - Acteurs du RGPD: rgpd/acteurs.md
      - Les 8 règles d'or: rgpd/regles-or.md
      - RGPD en collectivité: rgpd/collectivites.md
      - Travail et données personnelles: rgpd/travail-donnees-personnelles.md
      - Ressources PDF: rgpd/ressources-pdf.md
      - Enjeux avancés: rgpd/enjeux-avances.md

  - Systèmes Linux:
      - Vue d'ensemble: admin-systemes-linux/index.md
      - Itération 1 - Installation Debian 12 & comptes:
          - Kit Install - Environnement de travail: admin-systemes-linux/it-1/atelier1-kit-install.md
          - FHS - Arborescence Linux: admin-systemes-linux/it-1/atelier2-fhs.md
          - Identités Linux - passwd shadow group: admin-systemes-linux/it-1/atelier3-identites.md
          - Comptes AlpesNet - utilisateurs et services: admin-systemes-linux/it-1/atelier4-comptes-alpesnet.md
          - Cycle de vie des comptes Linux: admin-systemes-linux/it-1/atelier5-cycle-vie-comptes.md
          - Audit des comptes et droits sudo AlpesNet: admin-systemes-linux/it-1/atelier6-audit-comptes-sudo.md
          - Carnet de bord: admin-systemes-linux/it-1/carnet-bord-it1.md
          - audit alpesnet : admin-systemes-linux/it-1/audit-comptes-sudo-alpesnet.md
      - Itération 2 - Permissions et logs Linux:
          - Synthèse chmod, chown et umask: admin-systemes-linux/it-2/synthese-permissions-chmod-chown-umask.md
          - ACL Linux sur AlpesNet: admin-systemes-linux/it-2/atelier-acl-alpesnet.md
          - Logs système et journalctl AlpesNet: admin-systemes-linux/it-2/atelier-logs-journalctl-alpesnet.md
          - Rsyslog et logrotate SSH AlpesNet: admin-systemes-linux/it-2/atelier-rsyslog-logrotate-alpesnet.md
          - Audit des permissions AlpesNet: admin-systemes-linux/it-2/atelier-audit-permissions-alpesnet.md
          - Rapport audit permissions AlpesNet: admin-systemes-linux/it-2/audit-permissions-alpesnet.md
          - Carnet de bord : admin-systemes-linux/it-2/carnet-bord-it2.md
      - Itération 3 - Bash & automatisation:
          - Fondamentaux Bash et scripts simples: admin-systemes-linux/it-3/atelier1-bash-fondamentaux.md
          - Scripts d'administration pratiques: admin-systemes-linux/it-3/scripts-administration-pratiques.md
          - Planification cron AlpesNet: admin-systemes-linux/it-3/planification-cron-alpesnet.md
          - Script administration robuste AlpesNet: admin-systemes-linux/it-3/script-administration-robuste-alpesnet.md
          - Fonctions, arguments et trap Bash: admin-systemes-linux/it-3/fonctions-arguments-trap-bash.md
          - Carnet de bord : admin-systemes-linux/it-3/carnet-bord-it3.md
      - Itération 4 - Services Linux et durcissement:
          - Vue d'ensemble: admin-systemes-linux/it-4/index.md
          - NFS AlpesNet - partage réseau Linux: admin-systemes-linux/it-4/nfs-alpesnet.md
          - Samba AlpesNet - partage SMB/CIFS: admin-systemes-linux/it-4/samba-alpesnet.md
          - Durcissement Linux AlpesNet: admin-systemes-linux/it-4/durcissement-linux-alpesnet.md
          - Rapport de durcissement Linux AlpesNet: admin-systemes-linux/it-4/rapport-durcissement-linux-alpesnet.md
          - Script automatisation Itération 4: admin-systemes-linux/it-4/script-automatisation-it4.md
          - Rapport automatique Itération 4: admin-systemes-linux/it-4/rapport-it4-20260626_120855.md
      - Itération 5 - Sauvegarde et Nginx : 
          - Vue d'ensemble: admin-systemes-linux/it-5/index.md
          - Sauvegarde et restauration AlpesNet: admin-systemes-linux/it-5/sauvegarde-restauration-alpesnet.md
          - Autonomie 3 - Nginx sécurisé AlpesNet: admin-systemes-linux/it-5/autonomie-3-nginx-securise-alpesnet.md
          - Débriefing Nginx - comparer et améliorer: admin-systemes-linux/it-5/debriefing-nginx-reference-alpesnet.md
          - Rapport automatique Autonomie 3 : admin-systemes-linux/it-5/rapport-it5-20260626_141658.md

  - Réseaux :
      - Vue d'ensemble: admin-reseaux/index.md
      - Synthèse personnelle CC-01: admin-reseaux/synthese-personnelle-cc01.md
      - Itération 1 - TCP/IP et adressage:
          - Vue d'ensemble: admin-reseaux/iteration-1/index.md
          - Fondations TCP/IP & capture : admin-reseaux/iteration-1/fondations-tcpip-capture.md
          - Exercices Wireshark: admin-reseaux/iteration-1/wireshark.md
          - Adressage IPv4 et subnetting: admin-reseaux/iteration-1/adressage-ipv4-subnetting.md
          - Schémas réseau L1/L2/L3: admin-reseaux/iteration-1/ schémas_réseau_L1_L2_L3.md
          - Schéma réseau annoté : admin-reseaux/iteration-1/schema-reseau-alpesnet-complet.md
      - Itération 2 - Switching, ARP et VLANs:
          - Vue d'ensemble: admin-reseaux/iteration-2/index.md
          - Commutation et VLANs: admin-reseaux/iteration-2/synthese_switching_arp_stp.md
          - GNS3 tables mac & arp: admin-reseaux/iteration-2/gns3_mac_arp.md
          - Synthese VLANs: admin-reseaux/iteration-2/synthese_vlans.md
          - exercice facultatif - STP avancé : admin-reseaux/iteration-2/stp_avance.md
      - Itération 3 - Routage:
          - Vue d'ensemble: admin-reseaux/iteration-3/index.md
          - Routage statique: admin-reseaux/iteration-3/routage-statique.md
          - Routage dynamique: admin-reseaux/iteration-3/routage-dynamique-OSPF.md
      - Itération 4 - Services réseau:
          - Vue d'ensemble: admin-reseaux/iteration-4/index.md
          - Synthèse DHCP: admin-reseaux/iteration-4/synthese-dhcp.md
          - TP DHCP et VLANs: admin-reseaux/iteration-4/dhcp-vlans-gns3.md
          - Nat et PAT: admin-reseaux/iteration-4/nat-pat.md
          - TP NAT/PAT GNS3: admin-reseaux/iteration-4/tp-nat-pat-gns3.md
          - DNS interne: admin-reseaux/iteration-4/dns.md
          - Finalisation AlpesNet: admin-reseaux/iteration-4/finalisation-infrastructure-alpesnet.md
      - Itération 5 - Diagnostic et automatisation:
          - Vue d'ensemble: admin-reseaux/iteration-5/index.md
          - Méthode de diagnostic OSI: admin-reseaux/iteration-5/methode-diagnostic-osi.md
          - Simulation pannes AlpesNet OSI: admin-reseaux/iteration-5/simulation-pannes-alpesnet-osi.md
          - Critères fiche dépannage AlpesNet: admin-reseaux/iteration-5/criteres-fiche-depannage-alpesnet.md
          - TP Wireshark GNS3 et réseau physique: admin-reseaux/iteration-5/tp-wireshark-gns3-reseau-physique.md
          - Synthèse automatisation Bash: admin-reseaux/iteration-5/synthese-automatisation-bash.md
          - Automatisation connectivité et sauvegarde: admin-reseaux/iteration-5/automatisation-connectivite-sauvegarde.md

  - Réseaux sécurisés :
    - Vue d'ensemble: admin-reseaux-securisation/index.md
    - Itération 1 - VLANs sécurisés et nftables:
        - Vue d'ensemble: admin-reseaux-securisation/it-1/index.md
        - Introduction du module et architecture sécurisée: admin-reseaux-securisation/it-1/atelier1.md
        - VLANs sécurisés et préparation du filtrage: admin-reseaux-securisation/it-1/atelier2.md
        - Filtrage réseau avec nftables: admin-reseaux-securisation/it-1/atelier3.md
        - Introduction au VLAN Hopping et tests d'attaque: admin-reseaux-securisation/it-1/atelier4.md
    - Itération 2 - pfSense et ACL:
        - Vue d'ensemble: admin-reseaux-securisation/it-2/index.md
        - Déploiement de pfSense: admin-reseaux-securisation/it-2/atelier1.md
        - Règles de filtrage et ACL avec pfSense: admin-reseaux-securisation/it-2/atelier2.md
        - Journalisation et analyse des logs pfSense: admin-reseaux-securisation/it-2/atelier3.md
        - Synthèse pfSense: admin-reseaux-securisation/it-2/synthese-pfsense.md
    - Itération 3 - OpenVPN:
        - Vue d'ensemble: admin-reseaux-securisation/it-3/index.md
        - Introduction aux VPN et architecture du TP: admin-reseaux-securisation/it-3/atelier1.md
        - Mise en place d'un VPN OpenVPN site-à-site: admin-reseaux-securisation/it-3/atelier2.md
        - Analyse Wireshark et logs OpenVPN: admin-reseaux-securisation/it-3/atelier3.md
    - Itération 4 - Zeek et corrélation:
        - Vue d'ensemble: admin-reseaux-securisation/it-4/index.md
        - Découverte de Zeek et architecture d'analyse réseau: admin-reseaux-securisation/it-4/atelier1.md
        - Installation et premiers logs Zeek: admin-reseaux-securisation/it-4/atelier2.md
        - Analyse des logs Zeek et détection d'attaques: admin-reseaux-securisation/it-4/atelier3.md
        - Corrélation et analyse forensique réseau: admin-reseaux-securisation/it-4/atelier4.md
    - Itération 5 - Incident, Spark et Fail2ban:
        - Vue d'ensemble: admin-reseaux-securisation/it-5/index.md
        - Réponse à incident et sécurisation d'une installation Spark : admin-reseaux-securisation/it-5/atelier1.md
        - Fail2ban SSH et script de bannissement IP : admin-reseaux-securisation/it-5/atelier2.md
    - Itération 6 - Challenge final:
        - Vue d'ensemble: admin-reseaux-securisation/it-6/index.md
        - Préparation défensive et validation de l'infrastructure : admin-reseaux-securisation/it-6/atelier1.md
        - Test depuis un PC d'un autre apprenant : admin-reseaux-securisation/it-6/test-pc-autre-apprenant.md
        - Préparation d'un CTF facile : admin-reseaux-securisation/it-6/preparation-ctf-facile.md
        
  - Pense-bête:
      - Vue d'ensemble: pense-bete/index.md
      - Liens utiles: pense-bete/liens-utiles.md
      - Commandes Linux PDF: pense-bete/commandes-linux.md
      - Intro AIS et RGPD:
          - Intro AIS: pense-bete/glossaire/intro-rgpd/intro-ais.md
          - RGPD: pense-bete/glossaire/intro-rgpd/rgpd.md
      - Système d’info & archi SI:
          - Itération 1 - Système d'information: pense-bete/glossaire/systeme-info/iteration-1.md
          - Itération 2 - Enjeux, risques et normes: pense-bete/glossaire/systeme-info/iteration-2.md
          - Itération 3 - Analyse d'architecture SI: pense-bete/glossaire/systeme-info/iteration-3.md
          - Itération 4 - Sécurité d'un SI: pense-bete/glossaire/systeme-info/iteration-4.md
      - Systèmes Linux:
          - Itération 1 - Installation et comptes: pense-bete/glossaire/admin-systemes-linux/it-1.md
          - Itération 2 - Permissions et logs: pense-bete/glossaire/admin-systemes-linux/it-2.md
          - Itération 3 - Bash et automatisation: pense-bete/glossaire/admin-systemes-linux/it-3.md
          - Itération 4 - Services Linux et NFS: pense-bete/glossaire/admin-systemes-linux/it-4.md
          - Itération 5 - Sauvegarde et Nginx: pense-bete/glossaire/admin-systemes-linux/it-5.md
      - Administration des réseaux:
          - Itération 1 - TCP/IP et adressage: pense-bete/glossaire/admin-reseaux/iteration-1.md
          - Itération 2 - Switching, ARP et VLANs: pense-bete/glossaire/admin-reseaux/iteration-2.md
          - Itération 3 - Routage: pense-bete/glossaire/admin-reseaux/iteration-3.md
          - Itération 4 - Services réseau: pense-bete/glossaire/admin-reseaux/iteration-4.md
          - Itération 5 - Diagnostic et automatisation: pense-bete/glossaire/admin-reseaux/iteration-5.md
      - Administration des réseaux - sécurisation:
          - Itération 1 - VLANs sécurisés et nftables: pense-bete/glossaire/admin-reseaux-securisation/it-1.md
          - Itération 2 - pfSense et ACL: pense-bete/glossaire/admin-reseaux-securisation/it-2.md
          - Itération 3 - OpenVPN: pense-bete/glossaire/admin-reseaux-securisation/it-3.md
          - Itération 4 - Zeek et corrélation: pense-bete/glossaire/admin-reseaux-securisation/it-4.md
          - Itération 5 - Incident, Spark et Fail2ban: pense-bete/glossaire/admin-reseaux-securisation/it-5.md
          - Itération 6 - Challenge final: pense-bete/glossaire/admin-reseaux-securisation/it-6.md
